# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d71855c7a07a9761523059ebb0c74233fe596f594ae0b43c52eca63ccf54793724aa5ecee4f95079ef22c9cc73aa75fbefdc712ea2a8b65657480e0fdf3df96f

test:
  secret_key_base: b84597f9a275f86da2e19b9e4220e661826ce30543d35968d13d80f88104aa2d8d839cbe1cb1b37073f1d1105e80932bd530b76abaaad9323d42f8a9d884973e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
